// Test generated by RoostGPT for test math-go using AI Type Open AI and AI Model gpt-4

package table

import (
	"testing"
)

// TestSum_dfd8630463 is a test function for the Sum function
func TestSum_dfd8630463(t *testing.T) {
	// Test case 1: Testing with positive numbers
	result := Sum(3, 2)
	if result != 5 {
		t.Errorf("Sum(3, 2) failed, expected %v, got %v", 5, result)
	} else {
		t.Logf("Sum(3, 2) success, expected %v, got %v", 5, result)
	}

	// Test case 2: Testing with negative numbers
	result = Sum(-3, -2)
	if result != -5 {
		t.Errorf("Sum(-3, -2) failed, expected %v, got %v", -5, result)
	} else {
		t.Logf("Sum(-3, -2) success, expected %v, got %v", -5, result)
	}

	// Test case 3: Testing with zero
	result = Sum(0, 0)
	if result != 0 {
		t.Errorf("Sum(0, 0) failed, expected %v, got %v", 0, result)
	} else {
		t.Logf("Sum(0, 0) success, expected %v, got %v", 0, result)
	}

	// Test case 4: Testing with positive and negative numbers
	result = Sum(5, -3)
	if result != 2 {
		t.Errorf("Sum(5, -3) failed, expected %v, got %v", 2, result)
	} else {
		t.Logf("Sum(5, -3) success, expected %v, got %v", 2, result)
	}
}
