// Test generated by RoostGPT for test math-go using AI Type Open AI and AI Model gpt-4

package main

import (
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/gin-gonic/gin"
)

// This function sets up the router for the application
func setupRouterTest() *gin.Engine {
	r := gin.Default()
	r.GET("/ping", func(c *gin.Context) {
		c.String(http.StatusOK, "pong")
	})
	return r
}

// TestMain_a2e85e6415 function is used to test the main function
func TestMain_a2e85e6415(t *testing.T) {
	router := setupRouterTest()

	// Test case 1: Testing for /ping route
	w := httptest.NewRecorder()
	req, _ := http.NewRequest("GET", "/ping", nil)
	router.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("Status should be ok, got %d", w.Code)
		t.Log("/ping route failed")
	} else {
		t.Log("/ping route passed")
	}

	// Test case 2: Testing for unknown route
	w = httptest.NewRecorder()
	req, _ = http.NewRequest("GET", "/unknown", nil)
	router.ServeHTTP(w, req)

	if w.Code != http.StatusNotFound {
		t.Errorf("Status should be 404, got %d", w.Code)
		t.Log("/unknown route failed")
	} else {
		t.Log("/unknown route passed")
	}
}
