// Test generated by RoostGPT for test math-go using AI Type Open AI and AI Model gpt-4

package normal

import (
	"testing"
)

// Sum function is declared in another file, so it's not required here

// TestSum_dfd8630463 is a test function for the Sum function
func TestSum_dfd8630463(t *testing.T) {
	// Test case where x and y are both positive
	result := Sum(2, 3)
	if result != 5 {
		t.Error("Expected 5, but got ", result)
	} else {
		t.Log("Success: Test case where x and y are both positive")
	}

	// Test case where x is positive and y is negative
	result = Sum(2, -3)
	if result != -1 {
		t.Error("Expected -1, but got ", result)
	} else {
		t.Log("Success: Test case where x is positive and y is negative")
	}

	// Test case where x and y are both zero
	result = Sum(0, 0)
	if result != 0 {
		t.Error("Expected 0, but got ", result)
	} else {
		t.Log("Success: Test case where x and y are both zero")
	}

	// Test case where x and y are both negative
	result = Sum(-2, -3)
	if result != -5 {
		t.Error("Expected -5, but got ", result)
	} else {
		t.Log("Success: Test case where x and y are both negative")
	}
}
